### ISSUE TITLE
Little bit of doc

### ISSUE THREAD

**Issue by alex-bender** [tsavola/wag#2]
Hello, that projects looks promising, (gate as well)
but it isn't clearly understandable how to use it right now (I'm not go dev),
so could you please provide a tiny bit of documentation on how to
build that tool and convert wasm into x86?
Thanks a lot!

**Comment by tsavola** [comment]
Hi

Wag is only the compiler component, not a runtime&mdash;or a linker. It's meant to be used programmatically as part of an application which provides a runtime one way or another. As such, it cannot really be used without writing some Go and assembler.

That said, I recently added the `wasys` program. It has a lightweight runtime which simply provides some Linux syscalls as wasm import functions. It may be useful for experimentation. It compiles the program, executes it, and throws it away. It's highly unsafe.

The purpose of wag is to be usable in an online setting, without being an incremental JIT compiler; to decouple the execution environment from the compilation environment. That's why it's so focused.

While it could be possible for wag to act like a traditional AOT compiler and spit out native object code files, I don't see many uses for that, except perhaps debugging with standard tools (which I would like). Still, the focus on fast compilation speed means that wag doesn't produce very optimized code.

Thanks for asking!

**Comment by alex-bender** [comment]
Thanks a lot!
Now I see the purpose. Probably it would be great to have such an explanation somewhere in the readme.md or so.
Thanks!
